name: Build PocketMine-MP.phar

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build server phar
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer
          coverage: none

      - name: Validate Composer
        run: composer validate --no-check-publish

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Build PHAR
        run: composer make-server

      - name: Upload PHAR
        uses: actions/upload-artifact@v4
        with:
          name: PocketMine-MP.phar
          path: PocketMine-MP.phar
          if-no-files-found: error
