name: Build PocketMine-MP.phar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup PocketMine PHP
        uses: pmmp/setup-php-action@4
        with:
          php-version: "8.2"

      - name: Build PHAR
        run: composer make-server

      - name: Upload PHAR
        uses: actions/upload-artifact@v4
        with:
          name: PocketMine-MP.phar
          path: PocketMine-MP.phar
